/* =============================================================================
 * SUPERMINE ADVENTURE service worker — offline play, installable, OPT-IN updates.
 * -----------------------------------------------------------------------------
 * UPDATE MODEL
 *   Bump VERSION on every deploy. The page registers with
 *   { updateViaCache: 'none' } and calls reg.update() on load, so a changed
 *   sw.js is noticed at launch and the new build is precached in the
 *   background. The new worker then WAITS — it does NOT take over. ui.js shows
 *   an "UPDATE READY" button on the TITLE SCREEN, and only that tap sends
 *   SKIP_WAITING. When the new worker takes control, ui.js reloads — and only
 *   ever from the title screen, never mid-descent, so a loaded hold six
 *   hundred metres down can't be destroyed by a deploy.
 *
 *   GET_VERSION lets the title screen display the build that is actually
 *   serving this session, rather than whatever string happens to be compiled
 *   into the page.
 *
 * WHY CACHE-FIRST, WHOLE-BUILD
 *   This is 19 classic <script> tags sharing one global `SM`, with a documented
 *   cross-module contract. Serving js/advhud.js from a new deploy alongside
 *   js/adv.js from an old one would break that contract in ways that are almost
 *   impossible to debug — a HUD reading a getter the older director does not
 *   export yet is the exact failure, and it has happened. One versioned cache
 *   per deploy means every file in a session comes from exactly ONE build.
 *
 * THE CACHE PREFIX IS NOT COSMETIC
 *   This game was split out of SUPERMINE, which uses the `supermine-` prefix
 *   and deletes every cache carrying it on activate. Both games can end up on
 *   the same origin. The prefix here is `supermine-adventure-`, the cleanup
 *   filter below matches that prefix and nothing else, and neither game may
 *   ever widen its filter to the other's caches. Getting this wrong evicts a
 *   perfectly good offline install of the other game every time this one
 *   activates.
 *
 * ALL PATHS ARE RELATIVE ('./x') so the app works from a GitHub Pages
 * subpath like /supermine-adventure/ as well as from a domain root.
 * ========================================================================== */

// Bump on EVERY deploy — this string is the whole update mechanism. Clients
// that already have a cache only notice a new build when VERSION changes.
// v2.0.0  ADVENTURE, STANDALONE. Split out of SUPERMINE v1.9.0: the campaign
//         is the whole game now. The time-attack director, the upgrade-gate
//         system, the classic terrain streamer and the entire classic HUD
//         (menu, pause card, run summary, local high scores) are gone; boot
//         lands on a title gate that opens straight into the slot picker.
//         Save records are untouched — the localStorage key is unchanged, so
//         an existing company loads exactly as it did.
// v2.1.0  VISUAL IDENTITY. New icon mark (a rig's headlight falling into rock —
//         generated by tools/make-icons.py, same three filenames, so the asset
//         list below is unchanged and only the BYTES differ), a real title
//         screen in ui.js buildTitle() with the mark rebuilt in CSS, and the
//         manifest/meta names aligned to it. Presentation only: no gameplay,
//         no save format and no module contract was touched. The bump is here
//         because a cached client would otherwise keep serving the old icons,
//         the old title and the old manifest forever.
// v2.2.0  THE LIFT IS A MANOEUVRE. Driving at the doors hands the machine to the
//         lift, which drives it the rest of the way in, shuts the leaves behind
//         it and only THEN opens the door menu; dismissing the menu runs the
//         mirror. And a descent and a ride both ARRIVE OUTSIDE now — the doors
//         open, the machine rolls out, and the run is already running, where
//         both used to land inside the cage with a panel to dismiss. Touches
//         adv.js (the clock and the state machine), vehicle.js (the scripted
//         path), advterrain.js (the catch line, the fade depth, the held doors)
//         and advhud.js (the panel drops on `lift:undocking`). No save format,
//         no module load order and no asset changed, so the list below is
//         unchanged; the bump is here because a cached client would otherwise
//         keep the old flow forever.
// v2.4.0  THE WHOLE-MAP BALANCE PASS, AND THE DRILL BECOMES A KEY.
//         The six paid mines are redesigned as one campaign: eighteen rungs
//         (rights + levels) whose dollars-per-unit-of-hold rises monotonically,
//         asserted over all 153 owned-vs-purchasable pairs at the drill era each
//         mine implies — the free starter mine no longer out-earns the first
//         paid one. Every price is now stated in HAULS (a level costs one full
//         haul of the rung above, a mine's rights four), every mine has a
//         distinct geological identity and signature mineral, and each mine's
//         deepest rung carries an uncuttable trace of the next mine's mineral.
//         AND, on the owner's instruction, "uncuttable" is designed early: the
//         ore hardness ladder is re-spaced against js/rig.js's drill caps so the
//         starter auger cuts only coal, copper and iron — silver sits at 9.0
//         against its cap of 8.5, so the guaranteed silver motherlode below Old
//         Creek's first lift is a wall on the first descent and a full hold once
//         the $1 000 bit is bought. Country rock is untouched, so driving feels
//         identical; only ore moved.
//         ...AND THE MECHANIC THAT MAKES THAT LEGIBLE, in the same build.
//         Above-cap material is now a TRUE REFUSAL: the damage rect is trimmed
//         off anything the bit cannot bite, so an uncuttable deposit takes zero
//         damage instead of being chipped to 45% and then refusing to break. The
//         contact throws sparks BACK off the face, lands a dead low clank
//         ('refuse'), and raises one HUD banner — "SILVER — TOO HARD FOR THIS
//         DRILL" — off a new rate-limited `drill:toohard` event. And the WORKSHOP
//         is on the lift menu, so the fix is one tap away from the wall: find it,
//         ride up, buy the bit, drive back out and cut it, all in one expedition.
//         Touches vehicle/effects/sound/advhud/adv/advui + style-adventure.css.
//         No save format change and no asset list change, so the list below is
//         unchanged; the bump is what gets a cached client the new code.
// v2.5.0  THE WARNING MOVES ONTO THE MACHINE, AND THE MAP BECOMES A REWARD.
//         A refused mineral now raises its message in WORLD SPACE over the rig —
//         "UPGRADE DRILL TO MINE SILVER" — where the player is actually looking,
//         and while that wall owns the story the generic ram-damage caption
//         stands down, so "hull damage" can no longer bury the real lesson.
//         AND the new-game flow starts at PREPARE DESCENT, not the world map:
//         a fresh company lands on the starter mine's prep screen, and the map
//         only opens once three levels of the starter mine are owned — announced
//         by a one-time notice in the lift, in the same voice as the level gate.
//         No save format change and no asset list change; the bump is what gets
//         a cached client the new flow.
const VERSION = 'v2.5.0';
const CACHE = `supermine-adventure-${VERSION}`;
const CACHE_PREFIX = 'supermine-adventure-';

const ASSETS = [
  './',
  './index.html',
  './manifest.webmanifest',
  './style.css',
  './style-adventure.css',
  './js/config.js',
  './js/events.js',
  './js/materials.js',
  './js/input.js',
  './js/camera.js',
  './js/particles.js',
  './js/vehicle.js',
  './js/effects.js',
  './js/sound.js',
  './js/ui.js',
  './js/mines.js',
  './js/rig.js',
  './js/save.js',
  './js/advterrain.js',
  './js/scanner.js',
  './js/joystick.js',
  './js/advhud.js',
  './js/advui.js',
  './js/adv.js',
  './js/main.js',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-512.png',
];

self.addEventListener('install', (event) => {
  // Deliberately NO skipWaiting(): once precached the new worker parks in
  // WAITING until the player accepts the update from the title screen.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('message', (event) => {
  const msg = event.data || {};
  if (msg.type === 'SKIP_WAITING') self.skipWaiting();
  if (msg.type === 'GET_VERSION' && event.ports[0]) {
    event.ports[0].postMessage({ version: VERSION });
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        // CACHE_PREFIX, never a looser match — see the header. A cache belonging
        // to the original SUPERMINE must survive this untouched.
        keys.filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE)
            .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((res) => {
        if (res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(request, copy));
        }
        return res;
      }).catch(() => (request.mode === 'navigate' ? caches.match('./index.html') : undefined));
    })
  );
});
